# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Advance(object):
    def setupUi(self, Advance):
        Advance.setObjectName("Advance")
        Advance.resize(260, 175)
        self.Login_Button_2 = QtWidgets.QPushButton(Advance)
        self.Login_Button_2.setGeometry(QtCore.QRect(70, 30, 113, 32))
        self.Login_Button_2.setObjectName("Login_Button_2")
        self.Login_Button_3 = QtWidgets.QPushButton(Advance)
        self.Login_Button_3.setGeometry(QtCore.QRect(70, 90, 113, 32))
        self.Login_Button_3.setObjectName("Login_Button_3")

        self.retranslateUi(Advance)
        QtCore.QMetaObject.connectSlotsByName(Advance)

    def retranslateUi(self, Advance):
        _translate = QtCore.QCoreApplication.translate
        Advance.setWindowTitle(_translate("Advance", "Advance"))
        self.Login_Button_2.setText(_translate("Advance", "Add a User"))
        self.Login_Button_2.setShortcut(_translate("Advance", "Return"))
        self.Login_Button_3.setText(_translate("Advance", "Delete a User"))
        self.Login_Button_3.setShortcut(_translate("Advance", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Advance = QtWidgets.QWidget()
    ui = Ui_Advance()
    ui.setupUi(Advance)
    Advance.show()
    sys.exit(app.exec_())
