# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Advance.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Function import *


# done
class Ui_Advance(object):
    def setupUi(self, Advance):
        Advance.setObjectName("Advance")
        Advance.resize(300, 300)
        self.Add_Button = QtWidgets.QPushButton(Advance)
        self.Add_Button.setGeometry(QtCore.QRect(70, 30, 161, 32))
        self.Add_Button.setObjectName("Add_Button")
        self.Delete_Button = QtWidgets.QPushButton(Advance)
        self.Delete_Button.setGeometry(QtCore.QRect(70, 90, 161, 32))
        self.Delete_Button.setObjectName("Delete_Button")
        self.Search_Button = QtWidgets.QPushButton(Advance)
        self.Search_Button.setGeometry(QtCore.QRect(70, 150, 161, 32))
        self.Search_Button.setObjectName("Search_Button")
        self.Login_history_Button = QtWidgets.QPushButton(Advance)
        self.Login_history_Button.setGeometry(QtCore.QRect(70, 210, 161, 32))
        self.Login_history_Button.setObjectName("Login_history_Button")

        self.retranslateUi(Advance)
        QtCore.QMetaObject.connectSlotsByName(Advance)


        # connect button to function 
        self.Delete_Button.clicked.connect(self.open_Delete_window)
        self.Add_Button.clicked.connect(self.open_Register_window)
        self.Login_history_Button.clicked.connect(self.open_Search_Login_history_window)
        self.Search_Button.clicked.connect(self.open_Search_window)



    def retranslateUi(self, Advance):
        _translate = QtCore.QCoreApplication.translate
        Advance.setWindowTitle(_translate("Advance", "Advance"))
        self.Add_Button.setText(_translate("Advance", "Add a User"))
        self.Add_Button.setShortcut(_translate("Advance", "Return"))
        self.Delete_Button.setText(_translate("Advance", "Delete a User"))
        self.Delete_Button.setShortcut(_translate("Advance", "Return"))
        self.Search_Button.setText(_translate("Advance", "Search/Edit a User"))
        self.Search_Button.setShortcut(_translate("Advance", "Return"))
        self.Login_history_Button.setText(_translate("Advance", "Check out login history"))
        self.Login_history_Button.setShortcut(_translate("Advance", "Return"))

    def open_Search_Login_history_window(self):
        self.Search_Login_history = QtWidgets.QWidget()
        self.Search_Login_history_ui = Ui_Search_Login_history()
        self.Search_Login_history_ui.setupUi(self.Search_Login_history)
        self.Search_Login_history.show()

    def open_Search_window(self):
        self.Search = QtWidgets.QWidget()
        self.Search_ui = Ui_Search()
        self.Search_ui.setupUi(self.Search)
        self.Search.show()

    def open_Register_window(self):
        self.Register = QtWidgets.QWidget()
        self.Register_ui = Ui_Register()
        self.Register_ui.setupUi(self.Register)
        self.Register.show()


    def open_Delete_window(self):
        self.Delete = QtWidgets.QWidget()
        self.Delete_ui = Ui_Delete()
        self.Delete_ui.setupUi(self.Delete)
        self.Delete.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Advance = QtWidgets.QWidget()
    ui = Ui_Advance()
    ui.setupUi(Advance)
    Advance.show()
    sys.exit(app.exec_())
