# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Delete_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Function import function_class
from Remove_confirm import Ui_Remove_confirm

class Ui_Delete_main(object):
    def setupUi(self, Delete_main):
        Delete_main.setObjectName("Delete_main")
        Delete_main.resize(442, 272)
        self.centralwidget = QtWidgets.QWidget(Delete_main)
        self.centralwidget.setObjectName("centralwidget")
        self.Delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_button.setGeometry(QtCore.QRect(160, 130, 113, 32))
        self.Delete_button.setObjectName("Delete_button")
        self.ID_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ID_input.setGeometry(QtCore.QRect(180, 100, 113, 21))
        self.ID_input.setText("")
        self.ID_input.setObjectName("ID_input")
        self.ID_label = QtWidgets.QLabel(self.centralwidget)
        self.ID_label.setGeometry(QtCore.QRect(140, 100, 81, 16))
        self.ID_label.setObjectName("ID_label")
        self.Delete_message = QtWidgets.QLabel(self.centralwidget)
        self.Delete_message.setGeometry(QtCore.QRect(120, 60, 201, 31))
        self.Delete_message.setObjectName("Delete_message")
        Delete_main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Delete_main)
        self.statusbar.setObjectName("statusbar")
        Delete_main.setStatusBar(self.statusbar)

        self.retranslateUi(Delete_main)
        QtCore.QMetaObject.connectSlotsByName(Delete_main)

        self.Delete_button.clicked.connect(lambda: delete_the_user(self.ID_input.text()))


    def retranslateUi(self, Delete_main):
        _translate = QtCore.QCoreApplication.translate
        Delete_main.setWindowTitle(_translate("Delete_main", "Delete_main"))
        self.Delete_button.setText(_translate("Delete_main", "Delete"))
        self.ID_label.setText(_translate("Delete_main", "ID"))
        self.Delete_message.setText(_translate("Delete_main", "Type the user ID to delete a user"))

    def open_Remove_confirm_window(self):
        self.Remove_confirm = QtWidgets.QDialog()
        self.ui = Ui_Remove_confirm()
        self.ui.setupUi(self.Remove_confirm)
        self.Remove_confirm.show()



def delete_the_user(userid):
    print("delete!!")
    print(str(userid))
    exist = f.check_ID_exist(userid)
    print("success!")
    if(exist):
        print("in if!!")
        ui.open_Remove_confirm_window()

if __name__ == "__main__":
    import sys
    f = function_class()
    app = QtWidgets.QApplication(sys.argv)
    Delete_main = QtWidgets.QMainWindow()
    ui = Ui_Delete_main()
    ui.setupUi(Delete_main)
    Delete_main.show()
    sys.exit(app.exec_())
