# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QStyledItemDelegate, QApplication, QTableWidget, QMessageBox
from Function import function_class



# done
class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(305, 240)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.Login_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Login_Button.setGeometry(QtCore.QRect(40, 110, 113, 32))
        self.Login_Button.setObjectName("Login_Button")
        self.UserID_Input = QtWidgets.QLineEdit(self.centralwidget)
        self.UserID_Input.setGeometry(QtCore.QRect(130, 30, 113, 21))
        self.UserID_Input.setText("")
        self.UserID_Input.setObjectName("UserID_Input")
        self.UserID_Label = QtWidgets.QLabel(self.centralwidget)
        self.UserID_Label.setGeometry(QtCore.QRect(50, 30, 60, 16))
        self.UserID_Label.setObjectName("UserID_Label")
        self.Password_Label = QtWidgets.QLabel(self.centralwidget)
        self.Password_Label.setGeometry(QtCore.QRect(50, 70, 60, 16))
        self.Password_Label.setObjectName("Password_Label")
        self.Password_Input = QtWidgets.QLineEdit(self.centralwidget)
        self.Password_Input.setGeometry(QtCore.QRect(130, 70, 113, 21))
        self.Password_Input.setText("")
        self.Password_Input.setObjectName("Password_Input")
        self.Error_Message_for_password = QtWidgets.QLabel(self.centralwidget)
        self.Error_Message_for_password.setGeometry(QtCore.QRect(50, 150, 241, 21))
        self.Error_Message_for_password.setObjectName("Error_Message_for_password")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(180, 110, 111, 31))
        self.checkBox.setObjectName("checkBox")
        self.Error_Message_for_permission = QtWidgets.QLabel(self.centralwidget)
        self.Error_Message_for_permission.setGeometry(QtCore.QRect(100, 150, 141, 21))
        self.Error_Message_for_permission.setObjectName("Error_Message_for_permission")
        self.Error_Message_for_ID = QtWidgets.QLabel(self.centralwidget)
        self.Error_Message_for_ID.setGeometry(QtCore.QRect(120, 150, 141, 21))
        self.Error_Message_for_ID.setObjectName("Error_Message_for_ID")
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)


        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

        # hide the error message
        self.Error_Message_for_password.setHidden(True) 
        self.Error_Message_for_permission.setHidden(True) 
        self.Error_Message_for_ID.setHidden(True)

        # connect button to function 
        self.Login_Button.clicked.connect(lambda: self.check_ID_password_function_handler(self.UserID_Input.text(), self.Password_Input.text()))
    
    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.Login_Button.setText(_translate("Login", "Login"))
        self.Login_Button.setShortcut(_translate("Login", "Return"))
        self.UserID_Label.setText(_translate("Login", "UserID"))
        self.Password_Label.setText(_translate("Login", "Password"))
        self.Error_Message_for_password.setText(_translate("Login", "Wrong Password! Please try again!"))
        self.checkBox.setText(_translate("Login", "Admin mode"))
        self.Error_Message_for_permission.setText(_translate("Login", "You are not an Admin!"))
        self.Error_Message_for_ID.setText(_translate("Login", "ID doesn\'t exist!"))

    def open_Concentrate_Advance_window(self):
        self.Concentrate_Advance = QtWidgets.QTabWidget()
        self.Concentrate_Advance_ui = Ui_Concentrate_Advance()
        self.Concentrate_Advance_ui.current_user_ID = self.UserID_Input.text()
        self.Concentrate_Advance_ui.setupUi(self.Concentrate_Advance)
        self.Concentrate_Advance.show()

    def open_Show_ID_window(self):
        self.Show_ID = QtWidgets.QMainWindow()
        self.Show_ID_ui = Ui_Show_ID()
        self.Show_ID_ui.current_user_ID = self.UserID_Input.text()
        self.Show_ID_ui.setupUi(self.Show_ID)  
        self.Show_ID.show()

    def open_Info_Editor_window(self):
        self.Info_Editor = QtWidgets.QWidget()
        self.Info_Editor_ui = Ui_Info_Editor()
        self.Info_Editor_ui.current_user_ID = self.UserID_Input.text()
        self.Info_Editor_ui.setupUi(self.Info_Editor)  
        self.Info_Editor.show()

    def check_ID_password_function_handler(self, userid, password):
        # initialize 
        ID_password_match = False
        ID_is_admin = False
        ID_exist = f.check_ID_exist(userid)


        # encrypt the password
        encrypted_password = f.encode_password(password)

        # check if id and password is correct
        ID_password_match = f.check_ID_password(userid, encrypted_password)
        # error handler
        if(ID_password_match == -1):
            return

        # check if user is admin
        ID_is_admin = f.check_ID_is_admin(userid)
        # error handler
        if(ID_is_admin == -1):
            return
        
        if(ID_password_match is True):
            # enter Advance mode
            if(ID_is_admin is True and self.checkBox.isChecked()):
                f.add_login_record(userid, "SUCCESS", "Login with Advance mode")
                self.open_Concentrate_Advance_window()
                Login.close()
            # Fail: Not admin but try to entering advance mode
            elif(ID_is_admin is False and self.checkBox.isChecked()):
                f.add_login_record(userid, "FAIL", "A normal user tries to enter Advance mode")
                self.Error_Message_for_permission.setHidden(False) 
                self.Error_Message_for_password.setHidden(True)
                self.Error_Message_for_ID.setHidden(True)
                return
            # Normal user mode
            else:
                self.open_Show_ID_window()
                self.open_Info_Editor_window()
                self.Info_Editor_ui.show_user_info_into_table()
                f.add_login_record(userid, "SUCCESS", "Login with normal user mode")
                Login.close()
        # Fail: ID doesn't exist        
        elif(ID_exist is False):
            self.Error_Message_for_permission.setHidden(True) 
            self.Error_Message_for_password.setHidden(True)
            self.Error_Message_for_ID.setHidden(False)
            return
        # Fail: ID doesn't match password
        elif(ID_password_match is False):
            f.add_login_record(userid, "FAIL", "ID and Password doesn't match")
            # display the error message
            self.Error_Message_for_password.setHidden(False) 
            self.Error_Message_for_permission.setHidden(True)
            self.Error_Message_for_ID.setHidden(True)
            return

# done        
class Ui_Register(object):
    # global variable
    default_password = "Point1"

    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(294, 402)
        self.ID_input = QtWidgets.QLineEdit(Register)
        self.ID_input.setGeometry(QtCore.QRect(112, 20, 141, 21))
        self.ID_input.setText("")
        self.ID_input.setObjectName("ID_input")
        self.Add_a_user_button = QtWidgets.QPushButton(Register)
        self.Add_a_user_button.setGeometry(QtCore.QRect(100, 300, 113, 32))
        self.Add_a_user_button.setObjectName("Add_a_user_button")
        self.Name_input = QtWidgets.QLineEdit(Register)
        self.Name_input.setGeometry(QtCore.QRect(112, 80, 141, 21))
        self.Name_input.setText("")
        self.Name_input.setObjectName("Name_input")
        self.Gender_label = QtWidgets.QLabel(Register)
        self.Gender_label.setGeometry(QtCore.QRect(30, 130, 81, 16))
        self.Gender_label.setObjectName("Gender_label")
        self.Name_label = QtWidgets.QLabel(Register)
        self.Name_label.setGeometry(QtCore.QRect(30, 80, 81, 16))
        self.Name_label.setObjectName("Name_label")
        self.ID_label = QtWidgets.QLabel(Register)
        self.ID_label.setGeometry(QtCore.QRect(30, 20, 81, 16))
        self.ID_label.setObjectName("ID_label")
        self.Male_button = QtWidgets.QRadioButton(Register)
        self.Male_button.setGeometry(QtCore.QRect(110, 130, 100, 20))
        self.Male_button.setObjectName("Male_button")
        self.Button_group_gender = QtWidgets.QButtonGroup(Register)
        self.Button_group_gender.setObjectName("Button_group_gender")
        self.Button_group_gender.addButton(self.Male_button)
        self.Female_button = QtWidgets.QRadioButton(Register)
        self.Female_button.setGeometry(QtCore.QRect(110, 160, 100, 20))
        self.Female_button.setObjectName("Female_button")
        self.Button_group_gender.addButton(self.Female_button)
        self.Permission_label = QtWidgets.QLabel(Register)
        self.Permission_label.setGeometry(QtCore.QRect(30, 230, 81, 16))
        self.Permission_label.setObjectName("Permission_label")
        self.Admin_button = QtWidgets.QRadioButton(Register)
        self.Admin_button.setGeometry(QtCore.QRect(110, 230, 100, 20))
        self.Admin_button.setObjectName("Admin_button")
        self.Button_group_permission = QtWidgets.QButtonGroup(Register)
        self.Button_group_permission.setObjectName("Button_group_permission")
        self.Button_group_permission.addButton(self.Admin_button)
        self.Normal_button = QtWidgets.QRadioButton(Register)
        self.Normal_button.setGeometry(QtCore.QRect(110, 260, 100, 20))
        self.Normal_button.setObjectName("Normal_button")
        self.Button_group_permission.addButton(self.Normal_button)
        self.ID_error_message = QtWidgets.QLabel(Register)
        self.ID_error_message.setGeometry(QtCore.QRect(150, 40, 101, 16))
        self.ID_error_message.setObjectName("ID_error_message")
        self.Register_error_message = QtWidgets.QLabel(Register)
        self.Register_error_message.setGeometry(QtCore.QRect(100, 350, 81, 20))
        self.Register_error_message.setObjectName("Register_error_message")
        self.Register_success_message = QtWidgets.QLabel(Register)
        self.Register_success_message.setGeometry(QtCore.QRect(60, 350, 211, 20))
        self.Register_success_message.setObjectName("Register_success_message")
        self.Other_button = QtWidgets.QRadioButton(Register)
        self.Other_button.setGeometry(QtCore.QRect(110, 190, 100, 20))
        self.Other_button.setObjectName("Other_button")
        self.Button_group_gender.addButton(self.Other_button)        
        self.line = QtWidgets.QFrame(Register)
        self.line.setGeometry(QtCore.QRect(30, 60, 251, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Register)
        self.line_2.setGeometry(QtCore.QRect(30, 110, 251, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Register)
        self.line_3.setGeometry(QtCore.QRect(30, 210, 251, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Register)
        self.line_4.setGeometry(QtCore.QRect(30, 280, 251, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        # hide the error message initially
        self.ID_error_message.setHidden(True) 
        self.Register_error_message.setHidden(True) 
        self.Register_success_message.setHidden(True)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)


        # connect button to function
        self.Add_a_user_button.clicked.connect(lambda: self.press_register(self.ID_input.text(), self.default_password, self.Name_input.text()))            
    
    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Register"))
        self.Add_a_user_button.setText(_translate("Register", "Add a user"))
        self.Gender_label.setText(_translate("Register", "Gender"))
        self.Name_label.setText(_translate("Register", "Name"))
        self.ID_label.setText(_translate("Register", "ID"))
        self.Male_button.setText(_translate("Register", "Male"))
        self.Female_button.setText(_translate("Register", "Female"))
        self.Permission_label.setText(_translate("Register", "Permission"))
        self.Admin_button.setText(_translate("Register", "Admin"))
        self.Normal_button.setText(_translate("Register", "Normal"))
        self.ID_error_message.setText(_translate("Register", "Invalid ID!"))
        self.Register_error_message.setText(_translate("Register", "Action failed!"))
        self.Register_success_message.setText(_translate("Register", "Successfully added the user!"))
        self.Other_button.setText(_translate("Register", "Others"))

    # helper function
    def press_register(self, userid, password, real_name):
        return_flag = False
        gender_flag = False
        admin_flag = False
        name_flag = False

        # handle invalid input
        if(f.check_ID_exist(userid) is True or userid == "" or len(userid) < 4 or f.has_invalid_character(userid)):
            self.ID_error_message.setHidden(False)
            return_flag = True
        elif(f.check_ID_exist(userid) is False):
            self.ID_error_message.setHidden(True)

        if(self.Male_button.isChecked() or self.Female_button.isChecked() or self.Other_button.isChecked()):
            gender_flag = True
        if(self.Admin_button.isChecked() or self.Normal_button.isChecked()):
            admin_flag = True
        if(real_name == ""):
            name_flag = True

        if(return_flag is True or name_flag is True or gender_flag is False or admin_flag is False ):
            self.Register_error_message.setHidden(False)
            self.Register_success_message.setHidden(True)
            return -1

        # transfer radio button information to string
        if(self.Male_button.isChecked()):
            gender = "MALE"
        elif(self.Female_button.isChecked()):
            gender = "FEMALE"
        elif(self.Other_button.isChecked()):
            gender = "OTHERS"            
        if(self.Admin_button.isChecked()):
            permission = "ADMIN"
        elif(self.Normal_button.isChecked()):
            permission = "USER" 
        

        # encode the password 

        # Just for checking
        # print(userid)
        # print(encrypted_password)
        # print(permission)
        # print(real_name)
        # print(gender)

        # add the user
        f.add_user(userid, f.encode_password(password), permission, real_name, gender)
        self.Register_error_message.setHidden(True)
        self.Register_success_message.setHidden(False)

# done
class Ui_Show_ID(object):
    current_user_ID = ''
    def setupUi(self, Show_ID):
        Show_ID.setObjectName("Show_ID")
        Show_ID.resize(400, 164)
        Show_ID.setMaximumSize(QtCore.QSize(400, 300))
        self.ID_Browser = QtWidgets.QTextBrowser(Show_ID)
        self.ID_Browser.setGeometry(QtCore.QRect(90, 50, 241, 21))
        self.ID_Browser.setObjectName("ID_Browser")
        self.ID_label = QtWidgets.QLabel(Show_ID)
        self.ID_label.setGeometry(QtCore.QRect(20, 50, 60, 16))
        self.ID_label.setObjectName("ID_label")

        self.retranslateUi(Show_ID)
        QtCore.QMetaObject.connectSlotsByName(Show_ID)

        self.ID_Browser.setText(self.current_user_ID)

    def retranslateUi(self, Show_ID):
        _translate = QtCore.QCoreApplication.translate
        Show_ID.setWindowTitle(_translate("Show_ID", "Show_ID"))
        self.ID_label.setText(_translate("Show_ID", "USER ID"))

# yet
class Ui_Concentrate_Advance(object):
    current_user_ID = ''
    def setupUi(self, Concentrate_Advance):
        Concentrate_Advance.setObjectName("Concentrate_Advance")
        Concentrate_Advance.resize(1150, 800)
        self.Search_Edit_Tab = QtWidgets.QWidget()
        self.Search_Edit_Tab.setObjectName("Search_Edit_Tab")
        self.Delete_User_button = QtWidgets.QPushButton(self.Search_Edit_Tab)
        self.Delete_User_button.setGeometry(QtCore.QRect(20, 580, 161, 32))
        self.Delete_User_button.setMinimumSize(QtCore.QSize(161, 32))
        self.Delete_User_button.setObjectName("Delete_User_button")
        self.Gender_label = QtWidgets.QLabel(self.Search_Edit_Tab)
        self.Gender_label.setGeometry(QtCore.QRect(50, 380, 81, 20))
        self.Gender_label.setMinimumSize(QtCore.QSize(81, 20))
        self.Gender_label.setObjectName("Gender_label")
        self.Show_all_button = QtWidgets.QPushButton(self.Search_Edit_Tab)
        self.Show_all_button.setGeometry(QtCore.QRect(20, 540, 161, 32))
        self.Show_all_button.setMinimumSize(QtCore.QSize(161, 32))
        self.Show_all_button.setObjectName("Show_all_button")
        self.Add_User_button = QtWidgets.QPushButton(self.Search_Edit_Tab)
        self.Add_User_button.setGeometry(QtCore.QRect(20, 620, 161, 32))
        self.Add_User_button.setMinimumSize(QtCore.QSize(161, 32))
        self.Add_User_button.setObjectName("Add_User_button")
        self.line_3 = QtWidgets.QFrame(self.Search_Edit_Tab)
        self.line_3.setGeometry(QtCore.QRect(60, 350, 201, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Name_label = QtWidgets.QLabel(self.Search_Edit_Tab)
        self.Name_label.setGeometry(QtCore.QRect(50, 140, 61, 16))
        self.Name_label.setMinimumSize(QtCore.QSize(61, 16))
        self.Name_label.setObjectName("Name_label")
        self.Female_button = QtWidgets.QRadioButton(self.Search_Edit_Tab)
        self.Female_button.setGeometry(QtCore.QRect(140, 410, 100, 20))
        self.Female_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Female_button.setObjectName("Female_button")
        self.line_2 = QtWidgets.QFrame(self.Search_Edit_Tab)
        self.line_2.setGeometry(QtCore.QRect(60, 220, 201, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Permission_button = QtWidgets.QPushButton(self.Search_Edit_Tab)
        self.Permission_button.setGeometry(QtCore.QRect(100, 310, 160, 30))
        self.Permission_button.setMinimumSize(QtCore.QSize(140, 30))
        self.Permission_button.setObjectName("Permission_button")
        self.ID_input = QtWidgets.QLineEdit(self.Search_Edit_Tab)
        self.ID_input.setGeometry(QtCore.QRect(120, 20, 141, 21))
        self.ID_input.setMinimumSize(QtCore.QSize(141, 21))
        self.ID_input.setText("")
        self.ID_input.setObjectName("ID_input")
        self.line_4 = QtWidgets.QFrame(self.Search_Edit_Tab)
        self.line_4.setGeometry(QtCore.QRect(60, 500, 201, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.Name_search_button = QtWidgets.QPushButton(self.Search_Edit_Tab)
        self.Name_search_button.setGeometry(QtCore.QRect(120, 180, 140, 30))
        self.Name_search_button.setMinimumSize(QtCore.QSize(140, 30))
        self.Name_search_button.setObjectName("Name_search_button")
        self.Others_button = QtWidgets.QRadioButton(self.Search_Edit_Tab)
        self.Others_button.setGeometry(QtCore.QRect(140, 440, 100, 20))
        self.Others_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Others_button.setObjectName("Others_button")
        self.ID_search_button = QtWidgets.QPushButton(self.Search_Edit_Tab)
        self.ID_search_button.setGeometry(QtCore.QRect(120, 60, 140, 30))
        self.ID_search_button.setMinimumSize(QtCore.QSize(0, 0))
        self.ID_search_button.setObjectName("ID_search_button")
        self.line = QtWidgets.QFrame(self.Search_Edit_Tab)
        self.line.setGeometry(QtCore.QRect(60, 100, 200, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Admin_button = QtWidgets.QRadioButton(self.Search_Edit_Tab)
        self.Admin_button.setGeometry(QtCore.QRect(140, 280, 100, 20))
        self.Admin_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Admin_button.setObjectName("Admin_button")
        self.Edit_error_message = QtWidgets.QLabel(self.Search_Edit_Tab)
        self.Edit_error_message.setGeometry(QtCore.QRect(200, 670, 81, 16))
        self.Edit_error_message.setMinimumSize(QtCore.QSize(71, 16))
        self.Edit_error_message.setObjectName("Edit_error_message")
        self.ID_label = QtWidgets.QLabel(self.Search_Edit_Tab)
        self.ID_label.setGeometry(QtCore.QRect(50, 20, 61, 16))
        self.ID_label.setMinimumSize(QtCore.QSize(61, 16))
        self.ID_label.setObjectName("ID_label")
        self.Display_table = QtWidgets.QTableWidget(self.Search_Edit_Tab)
        self.Display_table.setGeometry(QtCore.QRect(320, 10, 800, 730))
        self.Display_table.setMinimumSize(QtCore.QSize(800, 361))
        self.Display_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Display_table.setObjectName("Display_table")
        self.Display_table.setColumnCount(7)
        self.Display_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(6, item)
        self.Display_table.horizontalHeader().setVisible(True)
        self.Display_table.horizontalHeader().setCascadingSectionResizes(False)
        self.Display_table.horizontalHeader().setDefaultSectionSize(100)
        self.Display_table.horizontalHeader().setMinimumSectionSize(20)
        self.Display_table.horizontalHeader().setSortIndicatorShown(False)
        self.Display_table.horizontalHeader().setStretchLastSection(True)
        self.Gender_button = QtWidgets.QPushButton(self.Search_Edit_Tab)
        self.Gender_button.setGeometry(QtCore.QRect(100, 460, 160, 30))
        self.Gender_button.setMinimumSize(QtCore.QSize(160, 30))
        self.Gender_button.setObjectName("Gender_button")
        self.Male_button = QtWidgets.QRadioButton(self.Search_Edit_Tab)
        self.Male_button.setGeometry(QtCore.QRect(140, 380, 100, 20))
        self.Male_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Male_button.setObjectName("Male_button")
        self.Permission_label = QtWidgets.QLabel(self.Search_Edit_Tab)
        self.Permission_label.setGeometry(QtCore.QRect(50, 250, 81, 20))
        self.Permission_label.setMinimumSize(QtCore.QSize(81, 20))
        self.Permission_label.setObjectName("Permission_label")
        self.User_button = QtWidgets.QRadioButton(self.Search_Edit_Tab)
        self.User_button.setGeometry(QtCore.QRect(140, 250, 100, 20))
        self.User_button.setMinimumSize(QtCore.QSize(100, 20))
        self.User_button.setObjectName("User_button")
        self.Save_change_button = QtWidgets.QPushButton(self.Search_Edit_Tab)
        self.Save_change_button.setGeometry(QtCore.QRect(20, 660, 161, 32))
        self.Save_change_button.setMinimumSize(QtCore.QSize(161, 32))
        self.Save_change_button.setObjectName("Save_change_button")
        self.Name_input = QtWidgets.QLineEdit(self.Search_Edit_Tab)
        self.Name_input.setGeometry(QtCore.QRect(120, 140, 141, 21))
        self.Name_input.setMinimumSize(QtCore.QSize(141, 21))
        self.Name_input.setText("")
        self.Name_input.setObjectName("Name_input")
        Concentrate_Advance.addTab(self.Search_Edit_Tab, "")
        self.Login_History_Tab = QtWidgets.QWidget()
        self.Login_History_Tab.setObjectName("Login_History_Tab")
        self.Password_doesnt_match_ID_button = QtWidgets.QRadioButton(self.Login_History_Tab)
        self.Password_doesnt_match_ID_button.setGeometry(QtCore.QRect(50, 290, 211, 20))
        self.Password_doesnt_match_ID_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Password_doesnt_match_ID_button.setObjectName("Password_doesnt_match_ID_button")
        self.Success_button = QtWidgets.QRadioButton(self.Login_History_Tab)
        self.Success_button.setGeometry(QtCore.QRect(50, 140, 100, 20))
        self.Success_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Success_button.setObjectName("Success_button")
        self.ID_label_login_history = QtWidgets.QLabel(self.Login_History_Tab)
        self.ID_label_login_history.setGeometry(QtCore.QRect(50, 20, 61, 16))
        self.ID_label_login_history.setMinimumSize(QtCore.QSize(61, 16))
        self.ID_label_login_history.setObjectName("ID_label_login_history")
        self.ID_doesnt_exist_button = QtWidgets.QRadioButton(self.Login_History_Tab)
        self.ID_doesnt_exist_button.setGeometry(QtCore.QRect(50, 260, 121, 20))
        self.ID_doesnt_exist_button.setMinimumSize(QtCore.QSize(100, 20))
        self.ID_doesnt_exist_button.setObjectName("ID_doesnt_exist_button")
        self.ID_input_login_history = QtWidgets.QLineEdit(self.Login_History_Tab)
        self.ID_input_login_history.setGeometry(QtCore.QRect(120, 20, 141, 21))
        self.ID_input_login_history.setMinimumSize(QtCore.QSize(141, 21))
        self.ID_input_login_history.setText("")
        self.ID_input_login_history.setObjectName("ID_input_login_history")
        self.ID_search_button_login_history = QtWidgets.QPushButton(self.Login_History_Tab)
        self.ID_search_button_login_history.setGeometry(QtCore.QRect(120, 60, 140, 30))
        self.ID_search_button_login_history.setMinimumSize(QtCore.QSize(0, 0))
        self.ID_search_button_login_history.setObjectName("ID_search_button_login_history")
        self.Display_Login_info = QtWidgets.QTableWidget(self.Login_History_Tab)
        self.Display_Login_info.setGeometry(QtCore.QRect(320, 10, 800, 730))
        self.Display_Login_info.setObjectName("Display_Login_info")
        self.Display_Login_info.setColumnCount(4)
        self.Display_Login_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Display_Login_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_Login_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_Login_info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_Login_info.setHorizontalHeaderItem(3, item)
        self.Display_Login_info.horizontalHeader().setCascadingSectionResizes(False)
        self.Display_Login_info.horizontalHeader().setDefaultSectionSize(100)
        self.Display_Login_info.horizontalHeader().setStretchLastSection(True)
        self.Fail_button = QtWidgets.QRadioButton(self.Login_History_Tab)
        self.Fail_button.setGeometry(QtCore.QRect(150, 140, 100, 20))
        self.Fail_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Fail_button.setObjectName("Fail_button")
        self.Fail_type_button = QtWidgets.QPushButton(self.Login_History_Tab)
        self.Fail_type_button.setGeometry(QtCore.QRect(120, 350, 140, 30))
        self.Fail_type_button.setMinimumSize(QtCore.QSize(140, 30))
        self.Fail_type_button.setObjectName("Fail_type_button")
        self.Status_show_button = QtWidgets.QPushButton(self.Login_History_Tab)
        self.Status_show_button.setGeometry(QtCore.QRect(120, 180, 140, 30))
        self.Status_show_button.setMinimumSize(QtCore.QSize(140, 30))
        self.Status_show_button.setObjectName("Status_show_button")
        self.Show_all_button_login_history = QtWidgets.QPushButton(self.Login_History_Tab)
        self.Show_all_button_login_history.setGeometry(QtCore.QRect(120, 530, 140, 30))
        self.Show_all_button_login_history.setMinimumSize(QtCore.QSize(140, 30))
        self.Show_all_button_login_history.setObjectName("Show_all_button_login_history")
        self.line_5 = QtWidgets.QFrame(self.Login_History_Tab)
        self.line_5.setGeometry(QtCore.QRect(60, 100, 200, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.Login_History_Tab)
        self.line_6.setGeometry(QtCore.QRect(60, 220, 200, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.Login_History_Tab)
        self.line_7.setGeometry(QtCore.QRect(60, 380, 200, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.User_enter_advance_button = QtWidgets.QRadioButton(self.Login_History_Tab)
        self.User_enter_advance_button.setGeometry(QtCore.QRect(50, 320, 241, 20))
        self.User_enter_advance_button.setMinimumSize(QtCore.QSize(100, 20))
        self.User_enter_advance_button.setObjectName("User_enter_advance_button")
        self.Success_type_button = QtWidgets.QPushButton(self.Login_History_Tab)
        self.Success_type_button.setGeometry(QtCore.QRect(120, 470, 161, 32))
        self.Success_type_button.setMinimumSize(QtCore.QSize(141, 32))
        self.Success_type_button.setObjectName("Success_type_button")
        self.Normal_login_button = QtWidgets.QRadioButton(self.Login_History_Tab)
        self.Normal_login_button.setGeometry(QtCore.QRect(50, 410, 121, 20))
        self.Normal_login_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Normal_login_button.setObjectName("Normal_login_button")
        self.Advance_login_button = QtWidgets.QRadioButton(self.Login_History_Tab)
        self.Advance_login_button.setGeometry(QtCore.QRect(50, 440, 121, 20))
        self.Advance_login_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Advance_login_button.setObjectName("Advance_login_button")
        self.line_8 = QtWidgets.QFrame(self.Login_History_Tab)
        self.line_8.setGeometry(QtCore.QRect(60, 500, 200, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        Concentrate_Advance.addTab(self.Login_History_Tab, "")
        self.Plate_Scan_Tab = QtWidgets.QWidget()
        self.Plate_Scan_Tab.setObjectName("Plate_Scan_Tab")
        self.Display_Plate_Info = QtWidgets.QTableWidget(self.Plate_Scan_Tab)
        self.Display_Plate_Info.setGeometry(QtCore.QRect(320, 10, 800, 730))
        self.Display_Plate_Info.setObjectName("Display_Plate_Info")
        self.Display_Plate_Info.setColumnCount(4)
        self.Display_Plate_Info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Display_Plate_Info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_Plate_Info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_Plate_Info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_Plate_Info.setHorizontalHeaderItem(3, item)
        self.Display_Plate_Info.horizontalHeader().setCascadingSectionResizes(False)
        self.Display_Plate_Info.horizontalHeader().setDefaultSectionSize(190)
        self.Display_Plate_Info.horizontalHeader().setStretchLastSection(True)
        self.Save_change_button_Plate_Info = QtWidgets.QPushButton(self.Plate_Scan_Tab)
        self.Save_change_button_Plate_Info.setGeometry(QtCore.QRect(70, 400, 161, 32))
        self.Save_change_button_Plate_Info.setMinimumSize(QtCore.QSize(161, 32))
        self.Save_change_button_Plate_Info.setObjectName("Save_change_button_Plate_Info")
        self.Show_all_button_Plate_Info = QtWidgets.QPushButton(self.Plate_Scan_Tab)
        self.Show_all_button_Plate_Info.setGeometry(QtCore.QRect(80, 360, 140, 30))
        self.Show_all_button_Plate_Info.setMinimumSize(QtCore.QSize(140, 30))
        self.Show_all_button_Plate_Info.setObjectName("Show_all_button_Plate_Info")
        self.Plate_ID_label_Plate_Info = QtWidgets.QLabel(self.Plate_Scan_Tab)
        self.Plate_ID_label_Plate_Info.setGeometry(QtCore.QRect(50, 140, 61, 16))
        self.Plate_ID_label_Plate_Info.setMinimumSize(QtCore.QSize(61, 16))
        self.Plate_ID_label_Plate_Info.setObjectName("Plate_ID_label_Plate_Info")
        self.ID_search_button_Plate_Info = QtWidgets.QPushButton(self.Plate_Scan_Tab)
        self.ID_search_button_Plate_Info.setGeometry(QtCore.QRect(120, 60, 140, 30))
        self.ID_search_button_Plate_Info.setMinimumSize(QtCore.QSize(0, 0))
        self.ID_search_button_Plate_Info.setObjectName("ID_search_button_Plate_Info")
        self.Plate_ID_search_button_Plate_Info = QtWidgets.QPushButton(self.Plate_Scan_Tab)
        self.Plate_ID_search_button_Plate_Info.setGeometry(QtCore.QRect(120, 180, 140, 30))
        self.Plate_ID_search_button_Plate_Info.setMinimumSize(QtCore.QSize(140, 30))
        self.Plate_ID_search_button_Plate_Info.setObjectName("Plate_ID_search_button_Plate_Info")
        self.ID_label_Plate_Info = QtWidgets.QLabel(self.Plate_Scan_Tab)
        self.ID_label_Plate_Info.setGeometry(QtCore.QRect(50, 20, 61, 16))
        self.ID_label_Plate_Info.setMinimumSize(QtCore.QSize(61, 16))
        self.ID_label_Plate_Info.setObjectName("ID_label_Plate_Info")
        self.line_9 = QtWidgets.QFrame(self.Plate_Scan_Tab)
        self.line_9.setGeometry(QtCore.QRect(60, 220, 201, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.ID_input_Plate_Info = QtWidgets.QLineEdit(self.Plate_Scan_Tab)
        self.ID_input_Plate_Info.setGeometry(QtCore.QRect(120, 20, 141, 21))
        self.ID_input_Plate_Info.setMinimumSize(QtCore.QSize(141, 21))
        self.ID_input_Plate_Info.setText("")
        self.ID_input_Plate_Info.setObjectName("ID_input_Plate_Info")
        self.line_10 = QtWidgets.QFrame(self.Plate_Scan_Tab)
        self.line_10.setGeometry(QtCore.QRect(60, 100, 200, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.Plate_ID_input_Plate_Info = QtWidgets.QLineEdit(self.Plate_Scan_Tab)
        self.Plate_ID_input_Plate_Info.setGeometry(QtCore.QRect(120, 140, 141, 21))
        self.Plate_ID_input_Plate_Info.setMinimumSize(QtCore.QSize(141, 21))
        self.Plate_ID_input_Plate_Info.setText("")
        self.Plate_ID_input_Plate_Info.setObjectName("Plate_ID_input_Plate_Info")
        Concentrate_Advance.addTab(self.Plate_Scan_Tab, "")


        self.retranslateUi(Concentrate_Advance)
        Concentrate_Advance.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Concentrate_Advance)

# Modding for Search/Edit
        # adjust column size
        header = self.Display_table.horizontalHeader()   
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)    
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)    
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)    
        header.setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeToContents)    

        # hide the error message
        self.Edit_error_message.setHidden(True)


        # connect button to function
        self.Show_all_button.clicked.connect(lambda: self.show_all_user())
        self.ID_search_button.clicked.connect(lambda: self.show_user_by_id(self.ID_input.text()))
        self.Name_search_button.clicked.connect(lambda: self.show_user_by_name(self.Name_input.text()))
        self.Gender_button.clicked.connect(lambda: self.show_user_by_gender())
        self.Permission_button.clicked.connect(lambda: self.show_user_by_permission())
        self.Save_change_button.clicked.connect(lambda: self.get_data_from_table())
        self.Delete_User_button.clicked.connect(lambda: self.show_delete_confirm())
        self.Add_User_button.clicked.connect(lambda: self.open_Register_window())

# Modding for Login History
        # adjust column size
        header = self.Display_Login_info.horizontalHeader()   
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)    
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)    
   
        # connect button to function
        self.Show_all_button_login_history.clicked.connect(lambda: self.show_all_login_history())
        self.ID_search_button_login_history.clicked.connect(lambda: self.show_login_history_by_id(self.ID_input_login_history.text()))
        self.Status_show_button.clicked.connect(lambda: self.show_login_history_by_status())
        self.Fail_type_button.clicked.connect(lambda: self.show_login_history_by_fail_type())
        self.Success_type_button.clicked.connect(lambda: self.show_login_history_by_success_type())

        # let table be read only
        self.Display_Login_info.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)


    def retranslateUi(self, Concentrate_Advance):
        _translate = QtCore.QCoreApplication.translate
        Concentrate_Advance.setWindowTitle(_translate("Concentrate_Advance", "Concentrate_Advance"))
        self.Delete_User_button.setText(_translate("Concentrate_Advance", "Delete a User"))
        self.Gender_label.setText(_translate("Concentrate_Advance", "Gender"))
        self.Show_all_button.setText(_translate("Concentrate_Advance", "Show All Users"))
        self.Add_User_button.setText(_translate("Concentrate_Advance", "Add a User"))
        self.Name_label.setText(_translate("Concentrate_Advance", "Name"))
        self.Female_button.setText(_translate("Concentrate_Advance", "Female"))
        self.Permission_button.setText(_translate("Concentrate_Advance", "Search by Permission"))
        self.Name_search_button.setText(_translate("Concentrate_Advance", "Search by Name"))
        self.Others_button.setText(_translate("Concentrate_Advance", "Others"))
        self.ID_search_button.setText(_translate("Concentrate_Advance", "Search by ID"))
        self.Admin_button.setText(_translate("Concentrate_Advance", "Admin"))
        self.Edit_error_message.setText(_translate("Concentrate_Advance", "Invalid input!"))
        self.ID_label.setText(_translate("Concentrate_Advance", "ID"))
        item = self.Display_table.horizontalHeaderItem(0)
        item.setText(_translate("Concentrate_Advance", "Checkbox"))
        item = self.Display_table.horizontalHeaderItem(1)
        item.setText(_translate("Concentrate_Advance", "ID"))
        item = self.Display_table.horizontalHeaderItem(2)
        item.setText(_translate("Concentrate_Advance", "Password"))
        item = self.Display_table.horizontalHeaderItem(3)
        item.setText(_translate("Concentrate_Advance", "Permission"))
        item = self.Display_table.horizontalHeaderItem(4)
        item.setText(_translate("Concentrate_Advance", "Name"))
        item = self.Display_table.horizontalHeaderItem(5)
        item.setText(_translate("Concentrate_Advance", "Gender"))
        item = self.Display_table.horizontalHeaderItem(6)
        item.setText(_translate("Concentrate_Advance", "Plate amount"))
        self.Gender_button.setText(_translate("Concentrate_Advance", "Search by Gender"))
        self.Male_button.setText(_translate("Concentrate_Advance", "Male"))
        self.Permission_label.setText(_translate("Concentrate_Advance", "Permission"))
        self.User_button.setText(_translate("Concentrate_Advance", "User"))
        self.Save_change_button.setText(_translate("Concentrate_Advance", "Save change"))
        Concentrate_Advance.setTabText(Concentrate_Advance.indexOf(self.Search_Edit_Tab), _translate("Concentrate_Advance", "User info"))
        self.Password_doesnt_match_ID_button.setText(_translate("Concentrate_Advance", "Password doesn\'t match ID"))
        self.Success_button.setText(_translate("Concentrate_Advance", "Success"))
        self.ID_label_login_history.setText(_translate("Concentrate_Advance", "ID"))
        self.ID_doesnt_exist_button.setText(_translate("Concentrate_Advance", "ID doesn\'t exist"))
        self.ID_search_button_login_history.setText(_translate("Concentrate_Advance", "Search by ID"))
        item = self.Display_Login_info.horizontalHeaderItem(0)
        item.setText(_translate("Concentrate_Advance", "Login_ID"))
        item = self.Display_Login_info.horizontalHeaderItem(1)
        item.setText(_translate("Concentrate_Advance", "Login_Time"))
        item = self.Display_Login_info.horizontalHeaderItem(2)
        item.setText(_translate("Concentrate_Advance", "Login_Status"))
        item = self.Display_Login_info.horizontalHeaderItem(3)
        item.setText(_translate("Concentrate_Advance", "Fail_Type"))
        self.Fail_button.setText(_translate("Concentrate_Advance", "Fail "))
        self.Fail_type_button.setText(_translate("Concentrate_Advance", "Show by Fail type"))
        self.Status_show_button.setText(_translate("Concentrate_Advance", "Show by Status"))
        self.Show_all_button_login_history.setText(_translate("Concentrate_Advance", "Show All"))
        self.User_enter_advance_button.setText(_translate("Concentrate_Advance", "Normal user entered Advance mode"))
        self.Success_type_button.setText(_translate("Concentrate_Advance", "Show by Success type"))
        self.Normal_login_button.setText(_translate("Concentrate_Advance", "Normal login"))
        self.Advance_login_button.setText(_translate("Concentrate_Advance", "Advance login"))
        Concentrate_Advance.setTabText(Concentrate_Advance.indexOf(self.Login_History_Tab), _translate("Concentrate_Advance", "Login History"))
        item = self.Display_Plate_Info.horizontalHeaderItem(0)
        item.setText(_translate("Concentrate_Advance", "Plate_ID"))
        item = self.Display_Plate_Info.horizontalHeaderItem(1)
        item.setText(_translate("Concentrate_Advance", "User_ID"))
        __sortingEnabled = self.Display_Plate_Info.isSortingEnabled()
        self.Display_Plate_Info.setSortingEnabled(False)
        self.Display_Plate_Info.setSortingEnabled(__sortingEnabled)
        self.Save_change_button_Plate_Info.setText(_translate("Concentrate_Advance", "Save change"))
        self.Show_all_button_Plate_Info.setText(_translate("Concentrate_Advance", "Show All"))
        self.Plate_ID_label_Plate_Info.setText(_translate("Concentrate_Advance", "Plate ID"))
        self.ID_search_button_Plate_Info.setText(_translate("Concentrate_Advance", "Search by ID"))
        self.Plate_ID_search_button_Plate_Info.setText(_translate("Concentrate_Advance", "Search by Plate ID"))
        self.ID_label_Plate_Info.setText(_translate("Concentrate_Advance", "ID"))
        Concentrate_Advance.setTabText(Concentrate_Advance.indexOf(self.Plate_Scan_Tab), _translate("Concentrate_Advance", "Plate Scan"))



# Function for Search/Edit
    def lock_the_ID_Column(self):
        rows = self.Display_table.rowCount()
        for i in range(rows):
            item = self.Display_table.item(i, 1)
            item.setFlags(QtCore.Qt.ItemIsEnabled)

    def show_all_user(self):
        data = f.get_all_data_from_user_info()
        self.insert_data_into_table_Search_Edit(data)
        self.lock_the_ID_Column()
        
    def show_user_by_id(self, userid):
        data = f.get_data_from_user_info_contains_id(userid)
        self.insert_data_into_table_Search_Edit(data)
        self.lock_the_ID_Column()

    def show_user_by_name(self, name):
        data = f.get_data_from_user_info_contains_name(name)        
        self.insert_data_into_table_Search_Edit(data)
        self.lock_the_ID_Column()

    def show_user_by_permission(self):
        if(self.User_button.isChecked()):
            data = f.get_data_from_user_info_by_permission("USER")
        elif(self.Admin_button.isChecked()):  
            data = f.get_data_from_user_info_by_permission("ADMIN")
        else:
            data = f.get_data_from_user_info_by_permission(None)
        self.insert_data_into_table_Search_Edit(data)
        self.lock_the_ID_Column()

    def show_user_by_gender(self):
        if(self.Male_button.isChecked()):
            data = f.get_data_from_user_info_by_gender("MALE")
        elif(self.Female_button.isChecked()):  
            data = f.get_data_from_user_info_by_gender("FEMALE")
        elif(self.Others_button.isChecked()):
            data = f.get_data_from_user_info_by_gender("OTHERS")            
        else:
            data = f.get_data_from_user_info_by_gender(None)
        self.insert_data_into_table_Search_Edit(data) 
        self.lock_the_ID_Column()       

    def insert_data_into_table_Search_Edit(self, data):
        # initialize the table
        self.Display_table.setRowCount(0) 
        row = 0
        self.check_button_array = []
        for login_record in data:
            self.Display_table.insertRow(row)
            self.Display_table.setItem(row, 1, QtWidgets.QTableWidgetItem(login_record[0]))
            self.Display_table.setItem(row, 2, QtWidgets.QTableWidgetItem("************"))
            self.Display_table.setItem(row, 3, QtWidgets.QTableWidgetItem(login_record[2]))
            self.Display_table.setItem(row, 4, QtWidgets.QTableWidgetItem(login_record[3]))
            self.Display_table.setItem(row, 5, QtWidgets.QTableWidgetItem(login_record[4]))     
            self.Display_table.setItem(row, 6, QtWidgets.QTableWidgetItem(str(login_record[5]))) 
            
            # set a button to table
            check_box = QtWidgets.QCheckBox()
            self.Display_table.setCellWidget(row, 0, check_box)
            self.check_button_array.append(check_box)
            row = row+1
    # mod needed
    def get_data_from_table(self):
        # go through entire table row by row
        for row in range(self.Display_table.rowCount()):
            data = []
            for column in range(self.Display_table.columnCount()):
                if(self.Display_table.item(row, column) != None):
                    data.append(self.Display_table.item(row, column).text())

            # check if check box is checked (防呆機制)
            if(self.check_button_array[row].isChecked()):
                # check if input permission and gender fit format
                if(data[2] == "USER" or data[2] == "ADMIN"):
                    if(data[4] == "MALE" or data[4] == "FEMALE" or data[4] == "OTHERS"):
                        # update name, gender, and permission
                        f.update_data_to_user_info(data[0], None, data[2], data[3], data[4])
                        self.Edit_error_message.setHidden(True)
                else:
                    self.Edit_error_message.setHidden(False)
                    return

                # check if password had been changed
                if(data[1] != "************"):
                    # check if edited password fit format
                    if(f.check_password_availability(data[1])):
                        f.update_data_to_user_info(data[0], f.encode_password(data[1]), data[2], data[3], data[4])
                        self.Edit_error_message.setHidden(True)
                    else:
                        self.Edit_error_message.setHidden(False)
                        return

    def open_Register_window(self):
        self.Register = QtWidgets.QWidget()
        self.Register_ui = Ui_Register()
        self.Register_ui.setupUi(self.Register)
        self.Register.show()

    def delete_users(self):
        # go through entire table row by row
        for row in range(self.Display_table.rowCount()):
            data = []
            for column in range(self.Display_table.columnCount()):
                if(self.Display_table.item(row, column) != None):
                    data.append(self.Display_table.item(row, column).text())
            if(self.check_button_array[row].isChecked()):
                f.remove_user(data[0])

    def show_delete_confirm(self):
        confirm = QMessageBox()
        confirm.setWindowTitle("Delete Confirm")
        confirm.setText("Remove Users?")
        confirm.setStandardButtons(QMessageBox.Cancel | QMessageBox.Ok)
        confirm.setDefaultButton(QMessageBox.Cancel)
        confirm.accepted.connect(lambda: self.delete_users())
        x = confirm.exec_()


# Function for Login History
    # helper function
    def show_all_login_history(self):
        data = f.get_all_data_from_login_history()
        self.insert_data_into_table(data)
        
    def show_login_history_by_id(self, userid):
        data = f.get_data_from_login_history_by_id(userid)
        self.insert_data_into_table(data)
 
    def show_login_history_by_status(self):
        data = f.get_data_from_login_history_by_status(None)
        if(self.Success_button.isChecked()):
            data = f.get_data_from_login_history_by_status("SUCCESS")
        if(self.Fail_button.isChecked()):  
            data = f.get_data_from_login_history_by_status("FAIL")
        self.insert_data_into_table(data)

    def show_login_history_by_fail_type(self):
        data = f.get_data_from_login_history_by_fail_type(None)
        if(self.ID_doesnt_exist_button.isChecked()):
            data = f.get_data_from_login_history_by_fail_type("ID doesn't exist")
        if(self.Password_doesnt_match_ID_button.isChecked()):
            data = f.get_data_from_login_history_by_fail_type("ID and Password doesn't match")
        if(self.User_enter_advance_button.isChecked()):
            data = f.get_data_from_login_history_by_fail_type("A normal user tries to enter Advance mode")            
        self.insert_data_into_table(data)

    def show_login_history_by_success_type(self):
        data = f.get_data_from_login_history_by_success_type(None)
        if(self.Normal_login_button.isChecked()):
            data = f.get_data_from_login_history_by_success_type("Login with normal user mode")
        if(self.Advance_login_button.isChecked()):
            data = f.get_data_from_login_history_by_success_type("Login with Advance mode")
        self.insert_data_into_table(data)

    def insert_data_into_table(self, data):
        # initialize the table
        self.Display_Login_info.setRowCount(0) 
        row = 0

        for login_record in data:
            self.Display_Login_info.insertRow(row)
            self.Display_Login_info.setItem(row, 0, QtWidgets.QTableWidgetItem(login_record[0]))
            self.Display_Login_info.setItem(row, 1, QtWidgets.QTableWidgetItem(login_record[1]))
            self.Display_Login_info.setItem(row, 2, QtWidgets.QTableWidgetItem(login_record[2]))
            self.Display_Login_info.setItem(row, 3, QtWidgets.QTableWidgetItem(login_record[3]))
            row = row+1  

# done
class Ui_Info_Editor(object):
    current_user_ID = ''
    def setupUi(self, Info_Editor):
        Info_Editor.setObjectName("Info_Editor")
        Info_Editor.resize(820, 150)
        self.Save_change_button = QtWidgets.QPushButton(Info_Editor)
        self.Save_change_button.setGeometry(QtCore.QRect(320, 110, 161, 32))
        self.Save_change_button.setMinimumSize(QtCore.QSize(161, 32))
        self.Save_change_button.setObjectName("Save_change_button")
        self.Display_table = QtWidgets.QTableWidget(Info_Editor)
        self.Display_table.setGeometry(QtCore.QRect(40, 30, 741, 71))
        self.Display_table.setMinimumSize(QtCore.QSize(0, 0))
        self.Display_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Display_table.setObjectName("Display_table")
        self.Display_table.setColumnCount(7)
        self.Display_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(6, item)
        self.Display_table.horizontalHeader().setVisible(True)
        self.Display_table.horizontalHeader().setCascadingSectionResizes(False)
        self.Display_table.horizontalHeader().setDefaultSectionSize(100)
        self.Display_table.horizontalHeader().setMinimumSectionSize(20)
        self.Display_table.horizontalHeader().setSortIndicatorShown(False)
        self.Display_table.horizontalHeader().setStretchLastSection(True)
        self.Input_Invalid = QtWidgets.QLabel(Info_Editor)
        self.Input_Invalid.setGeometry(QtCore.QRect(510, 110, 81, 31))
        self.Input_Invalid.setObjectName("Input_Invalid")


        self.retranslateUi(Info_Editor)
        QtCore.QMetaObject.connectSlotsByName(Info_Editor)
        
        # hide the error message
        self.Input_Invalid.setHidden(True)

        # connect button to function 
        self.Save_change_button.clicked.connect(lambda: self.get_data_from_table())
    
    def retranslateUi(self, Info_Editor):
        _translate = QtCore.QCoreApplication.translate
        Info_Editor.setWindowTitle(_translate("Info_Editor", "Info_Editor"))
        self.Save_change_button.setText(_translate("Info_Editor", "Save change"))
        item = self.Display_table.horizontalHeaderItem(0)
        item.setText(_translate("Info_Editor", "Checkbox"))
        item = self.Display_table.horizontalHeaderItem(1)
        item.setText(_translate("Info_Editor", "ID"))
        item = self.Display_table.horizontalHeaderItem(2)
        item.setText(_translate("Info_Editor", "Password"))
        item = self.Display_table.horizontalHeaderItem(3)
        item.setText(_translate("Info_Editor", "Permission"))
        item = self.Display_table.horizontalHeaderItem(4)
        item.setText(_translate("Info_Editor", "Name"))
        item = self.Display_table.horizontalHeaderItem(5)
        item.setText(_translate("Info_Editor", "Gender"))
        item = self.Display_table.horizontalHeaderItem(6)
        item.setText(_translate("Info_Editor", "Plate amount"))
        self.Input_Invalid.setText(_translate("Info_Editor", "Invalid input!"))

    def show_user_info_into_table(self):
        data = f.get_data_from_user_info_by_id(self.current_user_ID)
        self.insert_data_into_table_Search_Edit(data)
        self.lock_the_ID_Column()

    def insert_data_into_table_Search_Edit(self, data):
        # initialize the table
        self.Display_table.setRowCount(0) 
        row = 0
        self.check_button_array = []
        for login_record in data:
            self.Display_table.insertRow(row)
            self.Display_table.setItem(row, 1, QtWidgets.QTableWidgetItem(login_record[0]))
            self.Display_table.setItem(row, 2, QtWidgets.QTableWidgetItem("************"))
            self.Display_table.setItem(row, 3, QtWidgets.QTableWidgetItem(login_record[2]))
            self.Display_table.setItem(row, 4, QtWidgets.QTableWidgetItem(login_record[3]))
            self.Display_table.setItem(row, 5, QtWidgets.QTableWidgetItem(login_record[4]))     
            self.Display_table.setItem(row, 6, QtWidgets.QTableWidgetItem(str(login_record[5]))) 
            
            # set a button to table
            check_box = QtWidgets.QCheckBox()
            self.Display_table.setCellWidget(row, 0, check_box)
            self.check_button_array.append(check_box)
            row = row+1

    def lock_the_ID_Column(self):
        rows = self.Display_table.rowCount()
        for i in range(rows):
            item = self.Display_table.item(i, 1)
            item.setFlags(QtCore.Qt.ItemIsEnabled)

    def get_data_from_table(self):
        # go through entire table row by row
        for row in range(self.Display_table.rowCount()):
            data = []
            for column in range(self.Display_table.columnCount()):
                if(self.Display_table.item(row, column) != None):
                    data.append(self.Display_table.item(row, column).text())

            # check if check box is checked (防呆機制)
            if(self.check_button_array[row].isChecked()):
                # check if input permission and gender fit format
                if(data[2] == "USER" or data[2] == "ADMIN"):
                    if(data[4] == "MALE" or data[4] == "FEMALE" or data[4] == "OTHERS"):
                        # update name, gender, and permission
                        f.update_data_to_user_info(data[0], None, data[2], data[3], data[4])
                        self.Input_Invalid.setHidden(True)

                else:
                    self.Input_Invalid.setHidden(False)
                    return

                # check if password had been changed
                if(data[1] != "************"):
                    # check if edited password fit format
                    if(f.check_password_availability(data[1])):
                        f.update_data_to_user_info(data[0], f.encode_password(data[1]), data[2], data[3], data[4])
                        self.Input_Invalid.setHidden(True)
                    else:
                        self.Input_Invalid.setHidden(False)
                        return



# main
if __name__ == "__main__":
    import sys
    f = function_class()
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    Loginui = Ui_Login()
    Loginui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())



'''
# done
class Ui_Advance(object):
    def setupUi(self, Advance):
        Advance.setObjectName("Advance")
        Advance.resize(300, 300)
        self.Add_Button = QtWidgets.QPushButton(Advance)
        self.Add_Button.setGeometry(QtCore.QRect(70, 30, 161, 32))
        self.Add_Button.setObjectName("Add_Button")
        self.Delete_Button = QtWidgets.QPushButton(Advance)
        self.Delete_Button.setGeometry(QtCore.QRect(70, 90, 161, 32))
        self.Delete_Button.setObjectName("Delete_Button")
        self.Search_Button = QtWidgets.QPushButton(Advance)
        self.Search_Button.setGeometry(QtCore.QRect(70, 150, 161, 32))
        self.Search_Button.setObjectName("Search_Button")
        self.Login_history_Button = QtWidgets.QPushButton(Advance)
        self.Login_history_Button.setGeometry(QtCore.QRect(70, 210, 161, 32))
        self.Login_history_Button.setObjectName("Login_history_Button")

        self.retranslateUi(Advance)
        QtCore.QMetaObject.connectSlotsByName(Advance)


        # connect button to function 
        self.Delete_Button.clicked.connect(self.open_Delete_window)
        self.Add_Button.clicked.connect(self.open_Register_window)
        self.Login_history_Button.clicked.connect(self.open_Search_Login_history_window)
        self.Search_Button.clicked.connect(self.open_Search_window)



    def retranslateUi(self, Advance):
        _translate = QtCore.QCoreApplication.translate
        Advance.setWindowTitle(_translate("Advance", "Advance"))
        self.Add_Button.setText(_translate("Advance", "Add a User"))
        self.Add_Button.setShortcut(_translate("Advance", "Return"))
        self.Delete_Button.setText(_translate("Advance", "Delete a User"))
        self.Delete_Button.setShortcut(_translate("Advance", "Return"))
        self.Search_Button.setText(_translate("Advance", "Search/Edit a User"))
        self.Search_Button.setShortcut(_translate("Advance", "Return"))
        self.Login_history_Button.setText(_translate("Advance", "Check out login history"))
        self.Login_history_Button.setShortcut(_translate("Advance", "Return"))

    def open_Search_Login_history_window(self):
        self.Search_Login_history = QtWidgets.QWidget()
        self.Search_Login_history_ui = Ui_Search_Login_history()
        self.Search_Login_history_ui.setupUi(self.Search_Login_history)
        self.Search_Login_history.show()

    def open_Search_window(self):
        self.Search = QtWidgets.QWidget()
        self.Search_ui = Ui_Search()
        self.Search_ui.setupUi(self.Search)
        self.Search.show()

    def open_Register_window(self):
        self.Register = QtWidgets.QWidget()
        self.Register_ui = Ui_Register()
        self.Register_ui.setupUi(self.Register)
        self.Register.show()


    def open_Delete_window(self):
        self.Delete = QtWidgets.QWidget()
        self.Delete_ui = Ui_Delete()
        self.Delete_ui.setupUi(self.Delete)
        self.Delete.show()
'''

'''
# done
class Ui_Delete(object):
    def setupUi(self, Delete):
        Delete.setObjectName("Delete")
        Delete.resize(250, 175)
        self.Delete_button = QtWidgets.QPushButton(Delete)
        self.Delete_button.setGeometry(QtCore.QRect(70, 80, 113, 32))
        self.Delete_button.setObjectName("Delete_button")
        self.ID_label = QtWidgets.QLabel(Delete)
        self.ID_label.setGeometry(QtCore.QRect(50, 50, 81, 16))
        self.ID_label.setObjectName("ID_label")
        self.ID_input = QtWidgets.QLineEdit(Delete)
        self.ID_input.setGeometry(QtCore.QRect(90, 50, 113, 21))
        self.ID_input.setText("")
        self.ID_input.setObjectName("ID_input")
        self.Delete_message = QtWidgets.QLabel(Delete)
        self.Delete_message.setGeometry(QtCore.QRect(30, 10, 201, 31))
        self.Delete_message.setObjectName("Delete_message")
        self.Delete_success_message = QtWidgets.QLabel(Delete)
        self.Delete_success_message.setGeometry(QtCore.QRect(80, 120, 151, 16))
        self.Delete_success_message.setObjectName("Delete_success_message")
        self.ID_Doesnt_Exist_message = QtWidgets.QLabel(Delete)
        self.ID_Doesnt_Exist_message.setGeometry(QtCore.QRect(80, 120, 151, 16))
        self.ID_Doesnt_Exist_message.setObjectName("ID_Doesnt_Exist_message")

        # hide the delete_success_message initially
        self.Delete_success_message.setHidden(True)
        self.ID_Doesnt_Exist_message.setHidden(True)


        self.retranslateUi(Delete)
        QtCore.QMetaObject.connectSlotsByName(Delete)

        self.Delete_button.clicked.connect(lambda: self.delete_the_user(self.ID_input.text()))

    def retranslateUi(self, Delete):
        _translate = QtCore.QCoreApplication.translate
        Delete.setWindowTitle(_translate("Delete", "Delete"))
        self.Delete_button.setText(_translate("Delete", "Delete"))
        self.ID_label.setText(_translate("Delete", "ID"))
        self.Delete_message.setText(_translate("Delete", "Type the user ID to delete a user"))
        self.Delete_success_message.setText(_translate("Delete", "Delete success!!"))
        self.ID_Doesnt_Exist_message.setText(_translate("Delete", "ID doesn't exist!!"))

    def open_Remove_confirm_window(self):
        self.Remove_confirm = QtWidgets.QDialog()
        self.Remove_confirm_ui = Ui_Remove_confirm()
        self.Remove_confirm_ui.setupUi(self.Remove_confirm)
        self.Remove_confirm.show()


    def delete_the_user(self, userid):
        print(str(userid))
        exist = f.check_ID_exist(userid)
        if(exist == True):
            self.open_Remove_confirm_window()
            self.ID_Doesnt_Exist_message.setHidden(True)
        else:
            self.ID_Doesnt_Exist_message.setHidden(False)
            self.Delete_success_message.setHidden(True)

'''

'''
# yet
class Ui_Search(object):
    # global variable
    check_button_array = []
    def setupUi(self, Search):
        Search.setObjectName("Search")
        Search.resize(1188, 787)
        self.Name_input = QtWidgets.QLineEdit(Search)
        self.Name_input.setGeometry(QtCore.QRect(150, 150, 141, 21))
        self.Name_input.setMinimumSize(QtCore.QSize(141, 21))
        self.Name_input.setText("")
        self.Name_input.setObjectName("Name_input")
        self.line = QtWidgets.QFrame(Search)
        self.line.setGeometry(QtCore.QRect(90, 110, 201, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ID_search_button = QtWidgets.QPushButton(Search)
        self.ID_search_button.setGeometry(QtCore.QRect(150, 70, 141, 32))
        self.ID_search_button.setMinimumSize(QtCore.QSize(141, 32))
        self.ID_search_button.setObjectName("ID_search_button")
        self.Permission_button = QtWidgets.QPushButton(Search)
        self.Permission_button.setGeometry(QtCore.QRect(130, 320, 161, 32))
        self.Permission_button.setMinimumSize(QtCore.QSize(161, 32))
        self.Permission_button.setObjectName("Permission_button")
        self.line_3 = QtWidgets.QFrame(Search)
        self.line_3.setGeometry(QtCore.QRect(80, 360, 201, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.ID_input = QtWidgets.QLineEdit(Search)
        self.ID_input.setGeometry(QtCore.QRect(150, 30, 141, 21))
        self.ID_input.setMinimumSize(QtCore.QSize(141, 21))
        self.ID_input.setText("")
        self.ID_input.setObjectName("ID_input")
        self.Show_all_button = QtWidgets.QPushButton(Search)
        self.Show_all_button.setGeometry(QtCore.QRect(50, 550, 161, 32))
        self.Show_all_button.setMinimumSize(QtCore.QSize(161, 32))
        self.Show_all_button.setObjectName("Show_all_button")
        self.Name_search_button = QtWidgets.QPushButton(Search)
        self.Name_search_button.setGeometry(QtCore.QRect(150, 190, 141, 32))
        self.Name_search_button.setMinimumSize(QtCore.QSize(141, 32))
        self.Name_search_button.setObjectName("Name_search_button")
        self.line_2 = QtWidgets.QFrame(Search)
        self.line_2.setGeometry(QtCore.QRect(80, 230, 201, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Display_table = QtWidgets.QTableWidget(Search)
        self.Display_table.setGeometry(QtCore.QRect(350, 20, 800, 731))
        self.Display_table.setMinimumSize(QtCore.QSize(800, 361))
        self.Display_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Display_table.setObjectName("Display_table")
        self.Display_table.setColumnCount(7)
        self.Display_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_table.setHorizontalHeaderItem(6, item)
        self.Display_table.horizontalHeader().setVisible(True)
        self.Display_table.horizontalHeader().setCascadingSectionResizes(False)
        self.Display_table.horizontalHeader().setDefaultSectionSize(100)
        self.Display_table.horizontalHeader().setMinimumSectionSize(20)
        self.Display_table.horizontalHeader().setSortIndicatorShown(False)
        self.Display_table.horizontalHeader().setStretchLastSection(True)
        self.Name_label = QtWidgets.QLabel(Search)
        self.Name_label.setGeometry(QtCore.QRect(80, 150, 61, 16))
        self.Name_label.setMinimumSize(QtCore.QSize(61, 16))
        self.Name_label.setObjectName("Name_label")
        self.Male_button = QtWidgets.QRadioButton(Search)
        self.Male_button.setGeometry(QtCore.QRect(170, 390, 100, 20))
        self.Male_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Male_button.setObjectName("Male_button")
        self.Edit_error_message = QtWidgets.QLabel(Search)
        self.Edit_error_message.setGeometry(QtCore.QRect(230, 680, 81, 16))
        self.Edit_error_message.setMinimumSize(QtCore.QSize(71, 16))
        self.Edit_error_message.setObjectName("Edit_error_message")
        self.Female_button = QtWidgets.QRadioButton(Search)
        self.Female_button.setGeometry(QtCore.QRect(170, 420, 100, 20))
        self.Female_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Female_button.setObjectName("Female_button")
        self.Save_change_button = QtWidgets.QPushButton(Search)
        self.Save_change_button.setGeometry(QtCore.QRect(50, 670, 161, 32))
        self.Save_change_button.setMinimumSize(QtCore.QSize(161, 32))
        self.Save_change_button.setObjectName("Save_change_button")
        self.Gender_button = QtWidgets.QPushButton(Search)
        self.Gender_button.setGeometry(QtCore.QRect(130, 470, 161, 32))
        self.Gender_button.setMinimumSize(QtCore.QSize(161, 32))
        self.Gender_button.setObjectName("Gender_button")
        self.Add_User_button = QtWidgets.QPushButton(Search)
        self.Add_User_button.setGeometry(QtCore.QRect(50, 630, 161, 32))
        self.Add_User_button.setMinimumSize(QtCore.QSize(161, 32))
        self.Add_User_button.setObjectName("Add_User_button")
        self.line_4 = QtWidgets.QFrame(Search)
        self.line_4.setGeometry(QtCore.QRect(80, 510, 201, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.Permission_label = QtWidgets.QLabel(Search)
        self.Permission_label.setGeometry(QtCore.QRect(80, 260, 81, 20))
        self.Permission_label.setMinimumSize(QtCore.QSize(81, 20))
        self.Permission_label.setObjectName("Permission_label")
        self.Delete_User_button = QtWidgets.QPushButton(Search)
        self.Delete_User_button.setGeometry(QtCore.QRect(50, 590, 161, 32))
        self.Delete_User_button.setMinimumSize(QtCore.QSize(161, 32))
        self.Delete_User_button.setObjectName("Delete_User_button")
        self.Others_button = QtWidgets.QRadioButton(Search)
        self.Others_button.setGeometry(QtCore.QRect(170, 450, 100, 20))
        self.Others_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Others_button.setObjectName("Others_button")
        self.ID_label = QtWidgets.QLabel(Search)
        self.ID_label.setGeometry(QtCore.QRect(80, 30, 61, 16))
        self.ID_label.setMinimumSize(QtCore.QSize(61, 16))
        self.ID_label.setObjectName("ID_label")
        self.Admin_button = QtWidgets.QRadioButton(Search)
        self.Admin_button.setGeometry(QtCore.QRect(170, 290, 100, 20))
        self.Admin_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Admin_button.setObjectName("Admin_button")
        self.Gender_label = QtWidgets.QLabel(Search)
        self.Gender_label.setGeometry(QtCore.QRect(80, 390, 81, 20))
        self.Gender_label.setMinimumSize(QtCore.QSize(81, 20))
        self.Gender_label.setObjectName("Gender_label")
        self.User_button = QtWidgets.QRadioButton(Search)
        self.User_button.setGeometry(QtCore.QRect(170, 260, 100, 20))
        self.User_button.setMinimumSize(QtCore.QSize(100, 20))
        self.User_button.setObjectName("User_button")

        self.retranslateUi(Search)
        QtCore.QMetaObject.connectSlotsByName(Search)

        # adjust column size
        header = self.Display_table.horizontalHeader()   
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)    
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)    
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)    
        header.setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeToContents)    

        # hide the error message
        self.Edit_error_message.setHidden(True)


        # connect button to function
        self.Show_all_button.clicked.connect(lambda: self.show_all_user())
        self.ID_search_button.clicked.connect(lambda: self.show_user_by_id(self.ID_input.text()))
        self.Name_search_button.clicked.connect(lambda: self.show_user_by_name(self.Name_input.text()))
        self.Gender_button.clicked.connect(lambda: self.show_user_by_gender())
        self.Permission_button.clicked.connect(lambda: self.show_user_by_permission())
        self.Save_change_button.clicked.connect(lambda: self.get_data_from_table())
        self.Delete_User_button.clicked.connect(lambda: self.open_Remove_confirm_window())
        self.Add_User_button.clicked.connect(lambda: self.open_Register_window())


    def retranslateUi(self, Search):
        _translate = QtCore.QCoreApplication.translate
        Search.setWindowTitle(_translate("Search", "Search/Edit"))
        self.ID_search_button.setText(_translate("Search", "Search by ID"))
        self.Permission_button.setText(_translate("Search", "Search by Permission"))
        self.Show_all_button.setText(_translate("Search", "Show All Users"))
        self.Name_search_button.setText(_translate("Search", "Search by Name"))
        item = self.Display_table.horizontalHeaderItem(0)
        item.setText(_translate("Search", "Checkbox"))
        item = self.Display_table.horizontalHeaderItem(1)
        item.setText(_translate("Search", "ID"))
        item = self.Display_table.horizontalHeaderItem(2)
        item.setText(_translate("Search", "Password"))
        item = self.Display_table.horizontalHeaderItem(3)
        item.setText(_translate("Search", "Permission"))
        item = self.Display_table.horizontalHeaderItem(4)
        item.setText(_translate("Search", "Name"))
        item = self.Display_table.horizontalHeaderItem(5)
        item.setText(_translate("Search", "Gender"))
        item = self.Display_table.horizontalHeaderItem(6)
        item.setText(_translate("Search", "Plate amount"))
        self.Name_label.setText(_translate("Search", "Name"))
        self.Male_button.setText(_translate("Search", "Male"))
        self.Edit_error_message.setText(_translate("Search", "Invalid input!"))
        self.Female_button.setText(_translate("Search", "Female"))
        self.Save_change_button.setText(_translate("Search", "Save change"))
        self.Gender_button.setText(_translate("Search", "Search by Gender"))
        self.Add_User_button.setText(_translate("Search", "Add a User"))
        self.Permission_label.setText(_translate("Search", "Permission"))
        self.Delete_User_button.setText(_translate("Search", "Delete a User"))
        self.Others_button.setText(_translate("Search", "Others"))
        self.ID_label.setText(_translate("Search", "ID"))
        self.Admin_button.setText(_translate("Search", "Admin"))
        self.Gender_label.setText(_translate("Search", "Gender"))
        self.User_button.setText(_translate("Search", "User"))

    def lock_the_ID_Column(self):
        rows = self.Display_table.rowCount()
        for i in range(rows):
            item = self.Display_table.item(i, 1)
            item.setFlags(QtCore.Qt.ItemIsEnabled)

    def show_all_user(self):
        data = f.get_all_data_from_user_info()
        self.insert_data_into_table(data)
        self.lock_the_ID_Column()
        
    def show_user_by_id(self, userid):
        data = f.get_data_from_user_info_by_id(userid)
        self.insert_data_into_table(data)
        self.lock_the_ID_Column()

    def show_user_by_name(self, name):
        data = f.get_data_from_user_info_by_name(name)        
        self.insert_data_into_table(data)
        self.lock_the_ID_Column()

    def show_user_by_permission(self):
        if(self.User_button.isChecked()):
            data = f.get_data_from_user_info_by_permission("USER")
        elif(self.Admin_button.isChecked()):  
            data = f.get_data_from_user_info_by_permission("ADMIN")
        else:
            data = f.get_data_from_user_info_by_permission(None)
        self.insert_data_into_table(data)
        self.lock_the_ID_Column()

    def show_user_by_gender(self):
        if(self.Male_button.isChecked()):
            data = f.get_data_from_user_info_by_gender("MALE")
        elif(self.Female_button.isChecked()):  
            data = f.get_data_from_user_info_by_gender("FEMALE")
        elif(self.Others_button.isChecked()):
            data = f.get_data_from_user_info_by_gender("OTHERS")            
        else:
            data = f.get_data_from_user_info_by_gender(None)
        self.insert_data_into_table(data) 
        self.lock_the_ID_Column()       


    def insert_data_into_table(self, data):
        # initialize the table
        self.Display_table.setRowCount(0) 
        row = 0
        self.check_button_array = []
        for login_record in data:
            self.Display_table.insertRow(row)
            self.Display_table.setItem(row, 1, QtWidgets.QTableWidgetItem(login_record[0]))
            self.Display_table.setItem(row, 2, QtWidgets.QTableWidgetItem("************"))
            self.Display_table.setItem(row, 3, QtWidgets.QTableWidgetItem(login_record[2]))
            self.Display_table.setItem(row, 4, QtWidgets.QTableWidgetItem(login_record[3]))
            self.Display_table.setItem(row, 5, QtWidgets.QTableWidgetItem(login_record[4]))     
            self.Display_table.setItem(row, 6, QtWidgets.QTableWidgetItem(str(login_record[5]))) 
            
            # set a button to table
            check_box = QtWidgets.QCheckBox()
            self.Display_table.setCellWidget(row, 0, check_box)
            self.check_button_array.append(check_box)
            row = row+1
    # mod needed
    def get_data_from_table(self):
        # go through entire table row by row
        for row in range(self.Display_table.rowCount()):
            data = []
            for column in range(self.Display_table.columnCount()):
                if(self.Display_table.item(row, column) != None):
                    data.append(self.Display_table.item(row, column).text())

            # check if check box is checked (防呆機制)
            if(self.check_button_array[row].isChecked()):
                # check if input permission and gender fit format
                if(data[2] == "USER" or data[2] == "ADMIN"):
                    if(data[4] == "MALE" or data[4] == "FEMALE" or data[4] == "OTHERS"):
                        # update name, gender, and permission
                        f.update_data_to_user_info(data[0], None, data[2], data[3], data[4])
                        self.Edit_error_message.setHidden(True)

                else:
                    self.Edit_error_message.setHidden(False)
                    return

                # check if password had been changed
                if(data[1] != "************"):
                    # check if edited password fit format
                    if(f.check_password_availability(data[1])):
                        f.update_data_to_user_info(data[0], f.encode_password(data[1]), data[2], data[3], data[4])
                        self.Edit_error_message.setHidden(True)
                    else:
                        self.Edit_error_message.setHidden(False)
                        return

    def open_Remove_confirm_window(self):
        self.Remove_confirm = QtWidgets.QDialog()
        self.Remove_confirm_ui = Ui_Remove_confirm()
        self.Remove_confirm_ui.setupUi(self.Remove_confirm)
        self.Remove_confirm.show()

    def open_Register_window(self):
        self.Register = QtWidgets.QWidget()
        self.Register_ui = Ui_Register()
        self.Register_ui.setupUi(self.Register)
        self.Register.show()
'''

'''
# done
class Ui_Search_Login_history(object):
    def setupUi(self, Search_Login_history):
        Search_Login_history.setObjectName("Search_Login_history")
        Search_Login_history.resize(800, 500)
        self.Display_Login_info = QtWidgets.QTableWidget(Search_Login_history)
        self.Display_Login_info.setGeometry(QtCore.QRect(30, 150, 720, 300))
        self.Display_Login_info.setObjectName("Display_Login_info")
        self.Display_Login_info.resizeColumnsToContents()
        self.Display_Login_info.setColumnCount(4)
        self.Display_Login_info.setRowCount(0)

        header = self.Display_Login_info.horizontalHeader()       
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeToContents)
        self.ID_search_button = QtWidgets.QPushButton(Search_Login_history)
        self.ID_search_button.setGeometry(QtCore.QRect(80, 90, 141, 32))
        self.ID_search_button.setMinimumSize(QtCore.QSize(141, 32))
        self.ID_search_button.setObjectName("ID_search_button")
        self.ID_label = QtWidgets.QLabel(Search_Login_history)
        self.ID_label.setGeometry(QtCore.QRect(30, 30, 61, 16))
        self.ID_label.setMinimumSize(QtCore.QSize(61, 16))
        self.ID_label.setObjectName("ID_label")
        self.ID_input = QtWidgets.QLineEdit(Search_Login_history)
        self.ID_input.setGeometry(QtCore.QRect(80, 30, 141, 21))
        self.ID_input.setMinimumSize(QtCore.QSize(141, 21))
        self.ID_input.setText("")
        self.ID_input.setObjectName("ID_input")
        self.line_4 = QtWidgets.QFrame(Search_Login_history)
        self.line_4.setGeometry(QtCore.QRect(230, 20, 20, 111))
        self.line_4.setMinimumSize(QtCore.QSize(20, 111))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.Fail_type_button = QtWidgets.QPushButton(Search_Login_history)
        self.Fail_type_button.setGeometry(QtCore.QRect(520, 90, 141, 32))
        self.Fail_type_button.setMinimumSize(QtCore.QSize(141, 32))
        self.Fail_type_button.setObjectName("Fail_type_button")
        self.ID_doesnt_exist_button = QtWidgets.QRadioButton(Search_Login_history)
        self.ID_doesnt_exist_button.setGeometry(QtCore.QRect(520, 30, 121, 20))
        self.ID_doesnt_exist_button.setMinimumSize(QtCore.QSize(100, 20))
        self.ID_doesnt_exist_button.setObjectName("ID_doesnt_exist_button")
        self.Password_doesnt_match_ID_button = QtWidgets.QRadioButton(Search_Login_history)
        self.Password_doesnt_match_ID_button.setGeometry(QtCore.QRect(520, 60, 211, 20))
        self.Password_doesnt_match_ID_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Password_doesnt_match_ID_button.setObjectName("Password_doesnt_match_ID_button")
        self.Fail_button = QtWidgets.QRadioButton(Search_Login_history)
        self.Fail_button.setGeometry(QtCore.QRect(280, 60, 100, 20))
        self.Fail_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Fail_button.setObjectName("Fail_button")
        self.Success_button = QtWidgets.QRadioButton(Search_Login_history)
        self.Success_button.setGeometry(QtCore.QRect(280, 30, 100, 20))
        self.Success_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Success_button.setObjectName("Success_button")
        self.Status_show_button = QtWidgets.QPushButton(Search_Login_history)
        self.Status_show_button.setGeometry(QtCore.QRect(280, 90, 161, 32))
        self.Status_show_button.setMinimumSize(QtCore.QSize(141, 32))
        self.Status_show_button.setObjectName("Status_show_button")
        self.Show_all_button = QtWidgets.QPushButton(Search_Login_history)
        self.Show_all_button.setGeometry(QtCore.QRect(330, 460, 141, 32))
        self.Show_all_button.setMinimumSize(QtCore.QSize(141, 32))
        self.Show_all_button.setObjectName("Show_all_button")

        self.retranslateUi(Search_Login_history)
        QtCore.QMetaObject.connectSlotsByName(Search_Login_history)

        # connect button to function
        self.Show_all_button.clicked.connect(lambda: self.show_all_login_history())
        self.ID_search_button.clicked.connect(lambda: self.show_login_history_by_id(self.ID_input.text()))
        self.Status_show_button.clicked.connect(lambda: self.show_login_history_by_status())
        self.Fail_type_button.clicked.connect(lambda: self.show_login_history_by_fail_type())
        
        # let table be read only
        self.Display_Login_info.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)


    def retranslateUi(self, Search_Login_history):
        _translate = QtCore.QCoreApplication.translate
        Search_Login_history.setWindowTitle(_translate("Search_Login_history", "Search_Login_history"))
        item = self.Display_Login_info.horizontalHeaderItem(0)
        item.setText(_translate("Search_Login_history", "Login_ID"))
        item = self.Display_Login_info.horizontalHeaderItem(1)
        item.setText(_translate("Search_Login_history", "Login_Time"))
        item = self.Display_Login_info.horizontalHeaderItem(2)
        item.setText(_translate("Search_Login_history", "Login_Status"))
        item = self.Display_Login_info.horizontalHeaderItem(3)
        item.setText(_translate("Search_Login_history", "Fail_Type"))
        self.ID_search_button.setText(_translate("Search_Login_history", "Search by ID"))
        self.ID_label.setText(_translate("Search_Login_history", "ID"))
        self.Fail_type_button.setText(_translate("Search_Login_history", "Search by Fail type"))
        self.ID_doesnt_exist_button.setText(_translate("Search_Login_history", "ID doesn\'t exist"))
        self.Password_doesnt_match_ID_button.setText(_translate("Search_Login_history", "Password doesn\'t match ID"))
        self.Fail_button.setText(_translate("Search_Login_history", "Fail "))
        self.Success_button.setText(_translate("Search_Login_history", "Success"))
        self.Status_show_button.setText(_translate("Search_Login_history", "Show by Status"))
        self.Show_all_button.setText(_translate("Search_Login_history", "Show All"))


    # helper function
    def show_all_login_history(self):
        data = f.get_all_data_from_login_history()
        self.insert_data_into_table(data)
        

    def show_login_history_by_id(self, userid):
        data = f.get_data_from_login_history_by_id(userid)
        self.insert_data_into_table(data)
 
    def show_login_history_by_status(self):
        data = f.get_data_from_login_history_by_status(None)
        if(self.Success_button.isChecked()):
            data = f.get_data_from_login_history_by_status("SUCCESS")
        if(self.Fail_button.isChecked()):  
            data = f.get_data_from_login_history_by_status("FAIL")
        self.insert_data_into_table(data)

    def show_login_history_by_fail_type(self):
        data = f.get_data_from_login_history_by_fail_type(None)
        if(self.ID_doesnt_exist_button.isChecked()):
            data = f.get_data_from_login_history_by_fail_type("ID doesn't exist")
        if(self.Password_doesnt_match_ID_button.isChecked()):
            data = f.get_data_from_login_history_by_fail_type("ID and Password doesn't match")
        self.insert_data_into_table(data)


    def insert_data_into_table(self, data):
        # initialize the table
        self.Display_Login_info.setRowCount(0) 
        row = 0

        for login_record in data:
            self.Display_Login_info.insertRow(row)
            self.Display_Login_info.setItem(row, 0, QtWidgets.QTableWidgetItem(login_record[0]))
            self.Display_Login_info.setItem(row, 1, QtWidgets.QTableWidgetItem(login_record[1]))
            self.Display_Login_info.setItem(row, 2, QtWidgets.QTableWidgetItem(login_record[2]))
            self.Display_Login_info.setItem(row, 3, QtWidgets.QTableWidgetItem(login_record[3]))
            row = row+1       
'''

'''
# done
class Ui_Remove_confirm(object):
    def setupUi(self, Remove_confirm):
        Remove_confirm.setObjectName("Remove_confirm")
        Remove_confirm.resize(250, 180)
        self.Confirm_buttons = QtWidgets.QDialogButtonBox(Remove_confirm)
        self.Confirm_buttons.setGeometry(QtCore.QRect(40, 90, 171, 31))
        self.Confirm_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.Confirm_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Confirm_buttons.setObjectName("Confirm_buttons")
        self.Confirm_message = QtWidgets.QTextBrowser(Remove_confirm)
        self.Confirm_message.setGeometry(QtCore.QRect(50, 40, 161, 31))
        self.Confirm_message.setObjectName("Confirm_message")

        self.retranslateUi(Remove_confirm)
        # These two lines will close the window after pressing buttons
        self.Confirm_buttons.accepted.connect(Remove_confirm.accept)
        self.Confirm_buttons.rejected.connect(Remove_confirm.reject)
        QtCore.QMetaObject.connectSlotsByName(Remove_confirm)

        # Function to remove the user
        self.Confirm_buttons.accepted.connect(lambda: Loginui.Concentrate_Advance_ui.delete_users())
        

    def retranslateUi(self, Remove_confirm):
        _translate = QtCore.QCoreApplication.translate
        Remove_confirm.setWindowTitle(_translate("Remove_confirm", "Remove_confirm"))
        self.Confirm_message.setHtml(_translate("Remove_confirm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Remove the user?</span></p></body></html>"))
'''
