# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Search_Login_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Search_Login_history(object):
    def setupUi(self, Search_Login_history):
        Search_Login_history.setObjectName("Search_Login_history")
        Search_Login_history.resize(778, 488)
        self.Display_Login_info = QtWidgets.QTableWidget(Search_Login_history)
        self.Display_Login_info.setGeometry(QtCore.QRect(30, 150, 721, 281))
        self.Display_Login_info.setObjectName("Display_Login_info")
        self.Display_Login_info.setColumnCount(4)
        self.Display_Login_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Display_Login_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_Login_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_Login_info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Display_Login_info.setHorizontalHeaderItem(3, item)
        self.Display_Login_info.horizontalHeader().setDefaultSectionSize(180)
        self.ID_search_button = QtWidgets.QPushButton(Search_Login_history)
        self.ID_search_button.setGeometry(QtCore.QRect(80, 90, 141, 32))
        self.ID_search_button.setMinimumSize(QtCore.QSize(141, 32))
        self.ID_search_button.setObjectName("ID_search_button")
        self.ID_label = QtWidgets.QLabel(Search_Login_history)
        self.ID_label.setGeometry(QtCore.QRect(30, 30, 61, 16))
        self.ID_label.setMinimumSize(QtCore.QSize(61, 16))
        self.ID_label.setObjectName("ID_label")
        self.ID_input = QtWidgets.QLineEdit(Search_Login_history)
        self.ID_input.setGeometry(QtCore.QRect(80, 30, 141, 21))
        self.ID_input.setMinimumSize(QtCore.QSize(141, 21))
        self.ID_input.setText("")
        self.ID_input.setObjectName("ID_input")
        self.line_4 = QtWidgets.QFrame(Search_Login_history)
        self.line_4.setGeometry(QtCore.QRect(230, 20, 20, 111))
        self.line_4.setMinimumSize(QtCore.QSize(20, 111))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.Fail_type_button = QtWidgets.QPushButton(Search_Login_history)
        self.Fail_type_button.setGeometry(QtCore.QRect(520, 90, 141, 32))
        self.Fail_type_button.setMinimumSize(QtCore.QSize(141, 32))
        self.Fail_type_button.setObjectName("Fail_type_button")
        self.ID_doesnt_exist_button = QtWidgets.QRadioButton(Search_Login_history)
        self.ID_doesnt_exist_button.setGeometry(QtCore.QRect(520, 30, 121, 20))
        self.ID_doesnt_exist_button.setMinimumSize(QtCore.QSize(100, 20))
        self.ID_doesnt_exist_button.setObjectName("ID_doesnt_exist_button")
        self.Password_doesnt_match_ID_button = QtWidgets.QRadioButton(Search_Login_history)
        self.Password_doesnt_match_ID_button.setGeometry(QtCore.QRect(520, 60, 211, 20))
        self.Password_doesnt_match_ID_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Password_doesnt_match_ID_button.setObjectName("Password_doesnt_match_ID_button")
        self.Fail_button = QtWidgets.QRadioButton(Search_Login_history)
        self.Fail_button.setGeometry(QtCore.QRect(280, 60, 100, 20))
        self.Fail_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Fail_button.setObjectName("Fail_button")
        self.Success_button = QtWidgets.QRadioButton(Search_Login_history)
        self.Success_button.setGeometry(QtCore.QRect(280, 30, 100, 20))
        self.Success_button.setMinimumSize(QtCore.QSize(100, 20))
        self.Success_button.setObjectName("Success_button")
        self.Status_show_button = QtWidgets.QPushButton(Search_Login_history)
        self.Status_show_button.setGeometry(QtCore.QRect(280, 90, 161, 32))
        self.Status_show_button.setMinimumSize(QtCore.QSize(141, 32))
        self.Status_show_button.setObjectName("Status_show_button")
        self.Show_all_button = QtWidgets.QPushButton(Search_Login_history)
        self.Show_all_button.setGeometry(QtCore.QRect(330, 440, 141, 32))
        self.Show_all_button.setMinimumSize(QtCore.QSize(141, 32))
        self.Show_all_button.setObjectName("Show_all_button")

        self.retranslateUi(Search_Login_history)
        QtCore.QMetaObject.connectSlotsByName(Search_Login_history)

    def retranslateUi(self, Search_Login_history):
        _translate = QtCore.QCoreApplication.translate
        Search_Login_history.setWindowTitle(_translate("Search_Login_history", "Search_Login_history"))
        item = self.Display_Login_info.horizontalHeaderItem(0)
        item.setText(_translate("Search_Login_history", "Login_ID"))
        item = self.Display_Login_info.horizontalHeaderItem(1)
        item.setText(_translate("Search_Login_history", "Login_Time"))
        item = self.Display_Login_info.horizontalHeaderItem(2)
        item.setText(_translate("Search_Login_history", "Login_Status"))
        item = self.Display_Login_info.horizontalHeaderItem(3)
        item.setText(_translate("Search_Login_history", "Fail_Type"))
        self.ID_search_button.setText(_translate("Search_Login_history", "Search by ID"))
        self.ID_label.setText(_translate("Search_Login_history", "ID"))
        self.Fail_type_button.setText(_translate("Search_Login_history", "Search by Fail type"))
        self.ID_doesnt_exist_button.setText(_translate("Search_Login_history", "ID doesn\'t exist"))
        self.Password_doesnt_match_ID_button.setText(_translate("Search_Login_history", "Password doesn\'t match ID"))
        self.Fail_button.setText(_translate("Search_Login_history", "Fail "))
        self.Success_button.setText(_translate("Search_Login_history", "Success"))
        self.Status_show_button.setText(_translate("Search_Login_history", "Show by Status"))
        self.Show_all_button.setText(_translate("Search_Login_history", "Show All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Search_Login_history = QtWidgets.QWidget()
    ui = Ui_Search_Login_history()
    ui.setupUi(Search_Login_history)
    Search_Login_history.show()
    sys.exit(app.exec_())
