# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Remove_confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDial
from Function import function_class

class Ui_Remove_confirm(object):
    def setupUi(self, Remove_confirm):
        Remove_confirm.setObjectName("Remove_confirm")
        Remove_confirm.resize(250, 180)
        self.Confirm_buttons = QtWidgets.QDialogButtonBox(Remove_confirm)
        self.Confirm_buttons.setGeometry(QtCore.QRect(40, 90, 171, 31))
        self.Confirm_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.Confirm_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Confirm_buttons.setObjectName("Confirm_buttons")
        self.Confirm_message = QtWidgets.QTextBrowser(Remove_confirm)
        self.Confirm_message.setGeometry(QtCore.QRect(50, 40, 161, 31))
        self.Confirm_message.setObjectName("Confirm_message")

        self.retranslateUi(Remove_confirm)
        # These two lines will close the window after pressing buttons
        self.Confirm_buttons.accepted.connect(Remove_confirm.accept)
        self.Confirm_buttons.rejected.connect(Remove_confirm.reject)
        QtCore.QMetaObject.connectSlotsByName(Remove_confirm)
        

        self.Confirm_buttons.rejected.connect(self.confirm_delete(ui.ID_input.text()))

    def confirm_delete(self, userid):
        function_class().remove_user(userid)

    def retranslateUi(self, Remove_confirm):
        _translate = QtCore.QCoreApplication.translate
        Remove_confirm.setWindowTitle(_translate("Remove_confirm", "Remove_confirm"))
        self.Confirm_message.setHtml(_translate("Remove_confirm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Remove the user?</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Remove_confirm = QtWidgets.QDialog()
    ui = Ui_Remove_confirm()
    ui.setupUi(Remove_confirm)
    Remove_confirm.show()
    sys.exit(app.exec_())
