# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Show_ID.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Show_ID(object):
    def setupUi(self, Show_ID):
        Show_ID.setObjectName("Show_ID")
        Show_ID.resize(400, 164)
        Show_ID.setMaximumSize(QtCore.QSize(400, 300))
        self.ID_Browser = QtWidgets.QTextBrowser(Show_ID)
        self.ID_Browser.setGeometry(QtCore.QRect(90, 50, 241, 21))
        self.ID_Browser.setObjectName("ID_Browser")
        self.ID_label = QtWidgets.QLabel(Show_ID)
        self.ID_label.setGeometry(QtCore.QRect(20, 50, 60, 16))
        self.ID_label.setObjectName("ID_label")

        self.retranslateUi(Show_ID)
        QtCore.QMetaObject.connectSlotsByName(Show_ID)

    def retranslateUi(self, Show_ID):
        _translate = QtCore.QCoreApplication.translate
        Show_ID.setWindowTitle(_translate("Show_ID", "Show_ID"))
        self.ID_label.setText(_translate("Show_ID", "USER ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Show_ID = QtWidgets.QWidget()
    ui = Ui_Show_ID()
    ui.setupUi(Show_ID)
    Show_ID.show()
    sys.exit(app.exec_())
